parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony_redis
    database_user: symfony_redis
    database_password: symfony_redis
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 588565e65ccc910c63ebfe5b1c2106f03c
    database_path: null
