# app/config/routing.yml
RedisAdminBundle_homepage:
    path:      /
    defaults:  { _controller: RedisAdminBundle:Default:index }
RedisAdminBundle_show:
    path:      /show/{db}/
    defaults:  { _controller: RedisAdminBundle:Default:show }
RedisAdminBundle_details:
    path:      /show/{db}/{key}/
    defaults:  { _controller: RedisAdminBundle:Default:details }    