parameters:
#    redis_admin.example.class: Redis\AdminBundle\Example

services:
#    redis_admin.example:
#        class: %redis_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
